### ISSUE TITLE
Unable to build new windows binaries, bootstrap-vue@1.5.1 SyntaxError

### ISSUE THREAD

**Issue by littleskunk** [storj-archived/storjshare-gui#772]
### Versions

Replace the values below with your own:

- **Operating System:** Windows 10
bootstrap-vue@1.5.1
node@v8.9.4 (PC) / node@v8.11.2 (Notebook)

### Expected Behavior

Please describe the program's expected behavior.

I would expect a working windows binary.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

npm install failed.
```
> bootstrap-vue@1.5.1 postinstall C:\github\storjshare-gui\app\node_modules\bootstrap-vue
> opencollective postinstall || exit 0


     *** Thank you for using bootstrap-vue! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/bootstrap-vue/donate

                    ***

(node:15304) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
added 407 packages in 60.81s
C:\github\storjshare-gui\node_modules\.bin\electron-rebuild:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined postinstall: `node ./tasks/app_npm_install && node ./node_modules/.bin/electron-rebuild`
npm ERR! Exit status 1
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. git clone https://github.com/braydonf/storjshare-gui -b sip9
2. cd storjshare-gui
3. npm install

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
